import Testing
import SwiftUI
@testable import DesignFoundation

@Suite("DFPriceLineItem")
struct DFPriceLineItemTests {
    @Test("holds label, amount, and emphasis")
    func holdsCoreValues() {
        let item = DFPriceLineItem(label: "Subtotal", amount: 89.97)
        #expect(item.label == "Subtotal")
        #expect(item.amount == 89.97)
        #expect(item.emphasis == .normal)
    }

    @Test("emphasis defaults to normal, can be set to total")
    func emphasisDefault() {
        let total = DFPriceLineItem(label: "Total", amount: 102.56, emphasis: .total)
        #expect(total.emphasis == .total)
    }

    @Test("auto-generated id is unique per instance")
    func autoGeneratedIDIsUnique() {
        let a = DFPriceLineItem(label: "A", amount: 1)
        let b = DFPriceLineItem(label: "B", amount: 2)
        #expect(a.id != b.id)
    }
}

@Suite("DFPriceSummaryTokens")
struct DFPriceSummaryTokensTests {
    @Test("default tokens are all nil (inherit from theme)")
    func defaultTokensAreNil() {
        #expect(DFPriceSummaryTokens.default.rowSpacing == nil)
    }
}
